### ISSUE TITLE
Store output in a database

### ISSUE THREAD

**Issue by fikovnik** [PRL-PRG/scalafix-rule-workshop#1]
It will be handy to store the output from the scalafix into a database. The schema will be fairly simple:

[![](http://yuml.me/e155debb)](http://yuml.me/edit/e155debb)

_fqn: fully qualified name, fqfn: fully qualified type name, fqtn: fully qualified type name, ..._

Basically, what we have so far, but link it with a project.

I guess we can go either with sqlite or with mysql (mariadb). The latter has the advantage that it supports concurrent access so the tool can be run in parallel with no conflicts. A docker instance can be created on node-200. But all depends how the process will be designed.

Given that it is difficult to run a rule that has dependencies to external libraries, I guess it is the easiest to keep it as it is and then transfer the data in using a separate tool. The steps might be the following:
- a script that updates the project settings to accommodate for scalafix
- a script that runs the rule
- a script that gathers the output and pushes to DB

If the above are wrapped in yet another script, it can be easily run using gnu parallel.

**Comment by blorente** [comment]
I agree with most of the approach, specifically with the overall process (setup, run, collect), and with keeping the rule as simple as possible, since the bulk of processing time will be spent copiling and running sbt, and the faster it goes the better (plus a small file tow work with). 

I personally hate SQL and have limited experience with it, but I must agree that it is the best tool if CSV is the best format for the visualization. The schema looks fine, and regarding which technology to use either is good - both have plugins for Python and Nodejs, strong documentation and SQL is equally hideous in both. I guess it will come down to which one is easier to set up, since I think that not even query performance will be an issue. So I'll try setting one up. If it's too hard, I'll switch.

As I mentioned, I favor either Nodejs or Python for creating the scripts, each with it's tradeoffs. If we need to interface with the database in particular ways once the data has been stored, maybe it would be easiest to setup a Node server. On the other hand, if we only need "csv dumps" from the database, perhaps Python would be best. Either way, Python is better for taking the raw data from projects and shoving it into the database, and Node is better to provide an interface to the DB. I'd like to hear thoughts on this.

**Comment by blorente** [comment]
Just one comment about the schema, how should we handle subprojects? For example, `ensime` has subprjects `core/`, `s-express`... Are each of these an entry in the db, or just `ensime`? 

The easiest way is to just have `ensime` be the project, but maybe separating by subproject can help with identifying the ImplicitContext pattern (if we have the same parameter being passed around in functions of different subrojects)

**Comment by fikovnik** [comment]
The project table should contain only the top-level project - what we get from github. The version probably the SHA-1 commit.

**Comment by blorente** [comment]
Good, got it. 

Is the path really necessary? I can't find a reason to keep it.

**Comment by fikovnik** [comment]
The idea was to allow the visualization to quickly open given file.

**Comment by blorente** [comment]
Okay, got it

**Comment by fikovnik** [comment]
This has been covered by the https://github.com/PRL-PRG/scalafix-rule-workshop/pull/7
