### ISSUE TITLE
Add missing kinds

### ISSUE THREAD

**Issue by fikovnik** [PRL-PRG/scalafix-rule-workshop#8]
We are still getting bunch of unknowns:

```
unknown: Denotation(IMPLICIT | MACRO, 'methodFor1', '[Q, R, P1] => (f: Function1[P1, ServiceCall[Q, R]])(implicit evidence$1: PathParamSerializer[P1]): ScalaMethodServiceCall[Q, R]')
```

**Comment by blorente** [comment]
That particular unknown (macros) was solved in [this commit](https://github.com/PRL-PRG/scalafix-rule-workshop/commit/89698fc5c5d8d9cd604aaf599c3733c15153bd8b). Please post here if you see other ones

**Comment by fikovnik** [comment]
Have not seen any other. Can you please update the DB as well. Thanks

**Comment by blorente** [comment]
Same as #4, the new data should have a more elegant way to deal with unknown kinds (it stores the flags instead, such as `IMPLICIT | MACRO`, to at least be able to group by flags). I haven't caught any more yet, but we never know.

I prefer to prioritize completing the pipeline before updating the data because it takes me too long to mess with SQL, but do tell if you'd like it updated right away.
